name: anaconda_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.6.0=hcec6c5f_0
  - blas=1.0=openblas
  - brotli-python=1.0.9=py312h6d0c2b6_9
  - brotlicffi=1.0.9.2=py312h6d0c2b6_1
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.19.1=h6c40b1e_0
  - ca-certificates=2025.7.15=hecd8cb5_0
  - cairo=1.16.0=h08824b9_6
  - certifi=2025.8.3=py312hecd8cb5_0
  - cffi=1.17.1=py312h9205ec4_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - contourpy=1.3.1=py312h1962661_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h6c40b1e_0
  - deprecated=1.2.13=py312hecd8cb5_0
  - eigen=3.4.0=ha357a0b_0
  - expat=2.7.1=h6d0c2b6_0
  - ffmpeg=6.1.1=hd2ef4e1_3
  - filelock=3.17.0=py312hecd8cb5_0
  - fontconfig=2.14.1=h269ac6a_3
  - fonttools=4.55.3=py312h46256e1_0
  - freetype=2.13.3=h02243ff_0
  - fribidi=1.0.10=haf1e3a3_0
  - fsspec=2025.7.0=py312he13d532_0
  - gdk-pixbuf=2.42.10=h688160f_2
  - gettext=0.21.0=h4e8c18a_2
  - giflib=5.2.2=h46256e1_0
  - glib=2.84.2=h918fcf5_0
  - glib-tools=2.84.2=h918fcf5_0
  - gmp=6.3.0=h6d0c2b6_0
  - gmpy2=2.2.1=py312h2cec913_0
  - graphite2=1.3.14=he9d5cce_1
  - gst-plugins-base=1.24.12=h25bb215_1
  - gstreamer=1.24.12=hccc03b2_1
  - gstreamer-orc=0.4.41=h16176e1_0
  - harfbuzz=10.2.0=h060d35a_1
  - hdf5=1.14.5=h80586a8_2
  - icu=73.1=hcec6c5f_0
  - idna=3.7=py312hecd8cb5_0
  - importlib-metadata=8.5.0=py312hecd8cb5_0
  - jinja2=3.1.6=py312hecd8cb5_0
  - jpeg=9e=h46256e1_3
  - kagglehub=0.2.7=py312hecd8cb5_0
  - kiwisolver=1.4.8=py312h6d0c2b6_0
  - krb5=1.20.1=h428f121_1
  - lame=3.100=h1de35cc_0
  - lcms2=2.16=h31d93a5_1
  - leptonica=1.82.0=h7d8ae9a_3
  - lerc=4.0.0=h6d0c2b6_0
  - libabseil=20250127.0=cxx17_h548131f_0
  - libarchive=3.7.7=h4c66a04_0
  - libavif=1.1.1=h46256e1_0
  - libcurl=8.14.1=h1448931_1
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h46256e1_0
  - libedit=3.1.20230828=h6c40b1e_0
  - libev=4.33=h9ed2024_1
  - libffi=3.4.4=hecd8cb5_1
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libglib=2.84.2=heb90364_0
  - libiconv=1.16=h6c40b1e_3
  - libnghttp2=1.57.0=h9beae6a_0
  - libogg=1.3.5=hca72f7f_1
  - libopenblas=0.3.29=h3f8574a_0
  - libopus=1.3.1=h46256e1_1
  - libpng=1.6.39=h6c40b1e_0
  - libpq=12.20=h184c1cd_0
  - libprotobuf=5.29.3=h66a43dd_1
  - librsvg=2.56.3=h3d4ac1e_2
  - libssh2=1.11.1=h3a17b82_0
  - libtheora=1.1.1=hca72f7f_3
  - libtiff=4.7.0=h2dfa3ea_0
  - libtorch=2.5.1=cpu_openblas_h87ba575_3
  - libuv=1.48.0=h46256e1_0
  - libvorbis=1.3.7=haf1e3a3_0
  - libvpx=1.13.1=hcec6c5f_0
  - libwebp=1.3.2=hc927772_1
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=19.1.7=h5048363_2
  - lz4-c=1.9.4=hcec6c5f_1
  - markupsafe=3.0.2=py312h46256e1_0
  - matplotlib=3.10.0=py312hecd8cb5_0
  - matplotlib-base=3.10.0=py312h919b35b_0
  - mpc=1.3.1=h46256e1_0
  - mpfr=4.2.1=h46256e1_0
  - mpmath=1.3.0=py312hecd8cb5_0
  - mysql=8.4.0=h5364baf_2
  - ncurses=6.5=h923df54_0
  - networkx=3.4.2=py312hecd8cb5_0
  - nomkl=3.0=0
  - numpy=2.3.1=py312hc3ad23b_0
  - numpy-base=2.3.1=py312heda3e1f_0
  - opencv=4.10.0=py312h894815f_6
  - openh264=2.1.1=h8346a28_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openssl=3.0.17=hee2dfae_0
  - opentelemetry-api=1.30.0=py312hecd8cb5_0
  - packaging=25.0=py312hecd8cb5_0
  - pango=1.50.7=h02415e8_2
  - pcre2=10.42=h9b97e30_1
  - pillow=11.3.0=py312h25d8182_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=hb254d66_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyparsing=3.2.0=py312hecd8cb5_0
  - pysocks=1.7.1=py312hecd8cb5_0
  - python=3.12.11=he8d2d4c_0
  - python-dateutil=2.9.0post0=py312hecd8cb5_2
  - pytorch=2.5.1=cpu_openblas_py312ha2d39c5_3
  - qtbase=6.7.2=h2d11ce5_0
  - readline=8.3=h49f2429_0
  - requests=2.32.4=py312hecd8cb5_0
  - setuptools=72.1.0=py312hecd8cb5_0
  - six=1.17.0=py312hecd8cb5_0
  - sleef=3.5.1=h6c40b1e_2
  - sqlite=3.50.2=hc8b0dd6_1
  - sympy=1.13.3=py312hecd8cb5_1
  - tesseract=5.2.0=h6d0c2b6_2
  - tk=8.6.15=h3a5a201_0
  - torchvision=0.20.1=cpu_py312h038c130_2
  - tornado=6.5.1=py312h46256e1_0
  - tqdm=4.67.1=py312h8e4b320_0
  - typing_extensions=4.12.2=py312hecd8cb5_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py312h46256e1_1
  - urllib3=2.5.0=py312hecd8cb5_0
  - wheel=0.45.1=py312hecd8cb5_0
  - wrapt=1.17.0=py312h46256e1_0
  - xz=5.6.4=h46256e1_1
  - zipp=3.21.0=py312hecd8cb5_0
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
  - pip:
      - anyio==4.12.0
      - click==8.3.1
      - git-filter-repo==2.47.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.1
      - pyyaml==6.0.3
      - safetensors==0.7.0
      - shellingham==1.5.4
      - timm==1.0.22
      - typer-slim==0.20.0
